services:
  - type: web
    name: dupaming-trader
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: "-Xmx384m -Xms384m"
